use crate::ftc_proto::{
    self,
    command_packet::{
        DEFAULT_OPMODE_GROUP, OPMODE_STOP, OpModeData, OpModeFlavor, RobotConfigurationFile,
    },
    hardware::device::HardwareDeviceType,
    time_packet::RobotOpmodeState,
};

#[derive(Clone, PartialEq, Debug)]
/// Data that we got about the robot itself
pub struct Robot {
    /// The last update we got from the robot
    pub active_opmode_state: Option<RobotOpmodeState>,

    /// The currently active opmode
    pub active_opmode: String,

    // The list of opmodes the robot has
    pub opmode_list: Option<Vec<OpModeData>>,

    /// The active configuration, if we've received one
    pub active_configuration: Option<RobotConfigurationFile>,

    /// The valid configuration types, if we're received them from the server
    pub configuration_types: Option<Vec<HardwareDeviceType>>,

    /// The last battery voltage we got
    pub battery_voltage: Option<f32>,

    /// When the last battery update was received
    pub last_battery_update: std::time::Instant,

    /// An active system warning message, if any
    pub warning_message: Option<String>,

    /// An active system error message, if any
    pub error_message: Option<String>,

    /// The telemetry display lines last received in a telemetry packet
    pub telemetry_list: Vec<String>,
}

impl Robot {
    /// Creates a new real robot status, that has no info in it yet
    pub fn new_empty() -> Robot {
        Robot {
            active_opmode_state: None,
            active_opmode: OPMODE_STOP.to_string(),
            opmode_list: None,
            active_configuration: None,
            battery_voltage: None,
            last_battery_update: std::time::Instant::now(),
            warning_message: None,
            error_message: None,
            telemetry_list: Vec::new(),
            configuration_types: None,
        }
    }

    /// Creates a new fake robot status, to test the renderers
    pub fn new_fake() -> Robot {
        Robot {
            active_opmode_state: Some(RobotOpmodeState::Running),
            opmode_list: Some(vec![
                OpModeData {
                    name: OPMODE_STOP.to_string(),
                    group: DEFAULT_OPMODE_GROUP.to_string(),
                    flavor: OpModeFlavor::System,
                    source: None,
                    system_opmode_display_name: None,
                },
                OpModeData {
                    name: "Robot".to_string(),
                    group: DEFAULT_OPMODE_GROUP.to_string(),
                    flavor: OpModeFlavor::Teleop,
                    source: None,
                    system_opmode_display_name: None,
                },
                OpModeData {
                    name: "CoolerRobot".to_string(),
                    group: DEFAULT_OPMODE_GROUP.to_string(),
                    flavor: OpModeFlavor::Teleop,
                    source: None,
                    system_opmode_display_name: None,
                },
                OpModeData {
                    name: "Autonomous".to_string(),
                    group: "jože".to_string(),
                    flavor: OpModeFlavor::Autonomous,
                    source: None,
                    system_opmode_display_name: None,
                },
                OpModeData {
                    name: "CoolerAutonomous".to_string(),
                    group: "jože".to_string(),
                    flavor: OpModeFlavor::Autonomous,
                    source: None,
                    system_opmode_display_name: None,
                },
                OpModeData {
                    name: "Bautonomous".to_string(),
                    group: DEFAULT_OPMODE_GROUP.to_string(),
                    flavor: OpModeFlavor::Autonomous,
                    source: None,
                    system_opmode_display_name: None,
                },
            ]),
            active_opmode: "Bautonomous".to_string(),
            active_configuration: None,
            error_message: None,
            warning_message: Some(String::from("Test warning message")),
            battery_voltage: Some(12.3),
            last_battery_update: std::time::Instant::now(),
            telemetry_list: vec![
                "leftY : 0".to_string(),
                "leftX : 0".to_string(),
                "rightX : 0".to_string(),
                "left front : -667".to_string(),
                "left back : 0".to_string(),
                "right front : -737".to_string(),
                "right back : 310".to_string(),
                "rokaLeft : -67".to_string(),
                "rokaRight : 67".to_string(),
                "wanted location before : 0".to_string(),
                "power to set : 0".to_string(),
                "left position : 982".to_string(),
                "lifterLeft : 982".to_string(),
                "lifterRight : 983".to_string(),
                "wantedlocation : 984.428".to_string(),
                "L:  : 0".to_string(),
                "D:  : -0".to_string(),
                "claw wanted position : 1".to_string(),
                "curent position : 1".to_string(),
            ],
            configuration_types: Some(vec![
                HardwareDeviceType {
                    flavor: ftc_proto::hardware::device::DeviceFlavor::Motor,
                    xml_tag: String::from("NeveRest60Gearmotor"),
                    name: String::from("NeveRest 60 Gearmotor"),
                    built_in: true,
                    is_deprecated: false,
                    is_external_libraries: false,
                    is_on_bot_java: false,
                    description: String::from(""),
                    xml_tag_aliases: vec![],
                    motor_extras: None,
                    servo_extras: None,
                },
                HardwareDeviceType {
                    flavor: ftc_proto::hardware::device::DeviceFlavor::Motor,
                    xml_tag: String::from("goBILDA5202SeriesMotor"),
                    name: String::from("GoBILDA 5202/3/4 series"),
                    built_in: true,
                    is_deprecated: false,
                    is_external_libraries: false,
                    is_on_bot_java: false,
                    description: String::from(""),
                    xml_tag_aliases: vec![],
                    motor_extras: None,
                    servo_extras: None,
                },
                HardwareDeviceType {
                    flavor: ftc_proto::hardware::device::DeviceFlavor::Motor,
                    xml_tag: String::from("TetrixMotor"),
                    name: String::from("Tetrix Motor"),
                    built_in: true,
                    is_deprecated: false,
                    is_external_libraries: false,
                    is_on_bot_java: false,
                    description: String::from(""),
                    xml_tag_aliases: vec![],
                    motor_extras: None,
                    servo_extras: None,
                },
                HardwareDeviceType {
                    flavor: ftc_proto::hardware::device::DeviceFlavor::Motor,
                    xml_tag: String::from("goBILDA5201SeriesMotor"),
                    name: String::from("GoBILDA 5201 series"),
                    built_in: true,
                    is_deprecated: false,
                    is_external_libraries: false,
                    is_on_bot_java: false,
                    description: String::from(""),
                    xml_tag_aliases: vec![],
                    motor_extras: None,
                    servo_extras: None,
                },
                HardwareDeviceType {
                    flavor: ftc_proto::hardware::device::DeviceFlavor::BuiltIn,
                    xml_tag: String::from("ServoHub"),
                    name: String::from("[Unknown]"),
                    built_in: false,
                    is_deprecated: false,
                    is_external_libraries: false,
                    is_on_bot_java: false,
                    description: String::from(""),
                    xml_tag_aliases: vec![],
                    motor_extras: None,
                    servo_extras: None,
                },
                HardwareDeviceType {
                    flavor: ftc_proto::hardware::device::DeviceFlavor::DigitalIO,
                    xml_tag: String::from("DigitalDevice"),
                    name: String::from("Digital Device"),
                    built_in: true,
                    is_deprecated: false,
                    is_external_libraries: false,
                    is_on_bot_java: false,
                    description: String::from(""),
                    xml_tag_aliases: vec![],
                    motor_extras: None,
                    servo_extras: None,
                },
                HardwareDeviceType {
                    flavor: ftc_proto::hardware::device::DeviceFlavor::Motor,
                    xml_tag: String::from("RevRobotics20HDHexMotor"),
                    name: String::from("REV Robotics 20:1 HD Hex Motor"),
                    built_in: true,
                    is_deprecated: false,
                    is_external_libraries: false,
                    is_on_bot_java: false,
                    description: String::from(""),
                    xml_tag_aliases: vec![],
                    motor_extras: None,
                    servo_extras: None,
                },
                HardwareDeviceType {
                    flavor: ftc_proto::hardware::device::DeviceFlavor::Motor,
                    xml_tag: String::from("Matrix12vMotor"),
                    name: String::from("Matrix 12v Motor"),
                    built_in: true,
                    is_deprecated: false,
                    is_external_libraries: false,
                    is_on_bot_java: false,
                    description: String::from(""),
                    xml_tag_aliases: vec![],
                    motor_extras: None,
                    servo_extras: None,
                },
                HardwareDeviceType {
                    flavor: ftc_proto::hardware::device::DeviceFlavor::AnalogSensor,
                    xml_tag: String::from("ModernRoboticsAnalogTouchSensor"),
                    name: String::from("MR Touch Sensor"),
                    built_in: true,
                    is_deprecated: false,
                    is_external_libraries: false,
                    is_on_bot_java: false,
                    description: String::from("a Modern Robotics touch sensor"),
                    xml_tag_aliases: vec![],
                    motor_extras: None,
                    servo_extras: None,
                },
                HardwareDeviceType {
                    flavor: ftc_proto::hardware::device::DeviceFlavor::BuiltIn,
                    xml_tag: String::from("LightSensor"),
                    name: String::from("[Unknown]"),
                    built_in: false,
                    is_deprecated: false,
                    is_external_libraries: false,
                    is_on_bot_java: false,
                    description: String::from(""),
                    xml_tag_aliases: vec![],
                    motor_extras: None,
                    servo_extras: None,
                },
                HardwareDeviceType {
                    flavor: ftc_proto::hardware::device::DeviceFlavor::I2C,
                    xml_tag: String::from("AdafruitBNO055IMU"),
                    name: String::from("Adafruit IMU"),
                    built_in: true,
                    is_deprecated: false,
                    is_external_libraries: false,
                    is_on_bot_java: false,
                    description: String::from("an Adafruit IMU"),
                    xml_tag_aliases: vec![],
                    motor_extras: None,
                    servo_extras: None,
                },
                HardwareDeviceType {
                    flavor: ftc_proto::hardware::device::DeviceFlavor::I2C,
                    xml_tag: String::from("RevExternalImu"),
                    name: String::from("REV 9-Axis IMU"),
                    built_in: true,
                    is_deprecated: false,
                    is_external_libraries: false,
                    is_on_bot_java: false,
                    description: String::from("a REV 9-Axis IMU"),
                    xml_tag_aliases: vec![],
                    motor_extras: None,
                    servo_extras: None,
                },
                HardwareDeviceType {
                    flavor: ftc_proto::hardware::device::DeviceFlavor::Servo,
                    xml_tag: String::from("RevBlinkinLedDriver"),
                    name: String::from("REV Blinkin LED Driver"),
                    built_in: true,
                    is_deprecated: false,
                    is_external_libraries: false,
                    is_on_bot_java: false,
                    description: String::from("a REV Blinkin LED Driver"),
                    xml_tag_aliases: vec![],
                    motor_extras: None,
                    servo_extras: None,
                },
                HardwareDeviceType {
                    flavor: ftc_proto::hardware::device::DeviceFlavor::BuiltIn,
                    xml_tag: String::from("Robot"),
                    name: String::from("[Unknown]"),
                    built_in: false,
                    is_deprecated: false,
                    is_external_libraries: false,
                    is_on_bot_java: false,
                    description: String::from(""),
                    xml_tag_aliases: vec![],
                    motor_extras: None,
                    servo_extras: None,
                },
                HardwareDeviceType {
                    flavor: ftc_proto::hardware::device::DeviceFlavor::I2C,
                    xml_tag: String::from("ModernRoboticsI2cCompassSensor"),
                    name: String::from("MR Compass Sensor"),
                    built_in: true,
                    is_deprecated: false,
                    is_external_libraries: false,
                    is_on_bot_java: false,
                    description: String::from("a MR compass sensor"),
                    xml_tag_aliases: vec![],
                    motor_extras: None,
                    servo_extras: None,
                },
                HardwareDeviceType {
                    flavor: ftc_proto::hardware::device::DeviceFlavor::I2C,
                    xml_tag: String::from("QWIIC_LED_STICK"),
                    name: String::from("SparkFun QWIIC LED Stick"),
                    built_in: false,
                    is_deprecated: false,
                    is_external_libraries: false,
                    is_on_bot_java: false,
                    description: String::from("a SparkFun QWIIC LED Stick"),
                    xml_tag_aliases: vec![],
                    motor_extras: None,
                    servo_extras: None,
                },
                HardwareDeviceType {
                    flavor: ftc_proto::hardware::device::DeviceFlavor::Motor,
                    xml_tag: String::from("RevRobotics40HDHexMotor"),
                    name: String::from("REV Robotics 40:1 HD Hex Motor"),
                    built_in: true,
                    is_deprecated: false,
                    is_external_libraries: false,
                    is_on_bot_java: false,
                    description: String::from(""),
                    xml_tag_aliases: vec![String::from("RevRoboticsHDHexMotor")],
                    motor_extras: None,
                    servo_extras: None,
                },
                HardwareDeviceType {
                    flavor: ftc_proto::hardware::device::DeviceFlavor::BuiltIn,
                    xml_tag: String::from("IrSeeker"),
                    name: String::from("[Unknown]"),
                    built_in: false,
                    is_deprecated: false,
                    is_external_libraries: false,
                    is_on_bot_java: false,
                    description: String::from(""),
                    xml_tag_aliases: vec![],
                    motor_extras: None,
                    servo_extras: None,
                },
                HardwareDeviceType {
                    flavor: ftc_proto::hardware::device::DeviceFlavor::DigitalIO,
                    xml_tag: String::from("RevTouchSensor"),
                    name: String::from("REV Touch Sensor"),
                    built_in: true,
                    is_deprecated: false,
                    is_external_libraries: false,
                    is_on_bot_java: false,
                    description: String::from("a REV touch sensor"),
                    xml_tag_aliases: vec![],
                    motor_extras: None,
                    servo_extras: None,
                },
                HardwareDeviceType {
                    flavor: ftc_proto::hardware::device::DeviceFlavor::I2C,
                    xml_tag: String::from("LynxEmbeddedIMU"),
                    name: String::from("REV internal IMU (BNO055)"),
                    built_in: true,
                    is_deprecated: false,
                    is_external_libraries: false,
                    is_on_bot_java: false,
                    description: String::from("an embedded IMU"),
                    xml_tag_aliases: vec![],
                    motor_extras: None,
                    servo_extras: None,
                },
                HardwareDeviceType {
                    flavor: ftc_proto::hardware::device::DeviceFlavor::BuiltIn,
                    xml_tag: String::from("Gyro"),
                    name: String::from("MR Gyro"),
                    built_in: false,
                    is_deprecated: false,
                    is_external_libraries: false,
                    is_on_bot_java: false,
                    description: String::from(""),
                    xml_tag_aliases: vec![],
                    motor_extras: None,
                    servo_extras: None,
                },
                HardwareDeviceType {
                    flavor: ftc_proto::hardware::device::DeviceFlavor::Motor,
                    xml_tag: String::from("NeveRest40Gearmotor"),
                    name: String::from("NeveRest 40 Gearmotor"),
                    built_in: true,
                    is_deprecated: false,
                    is_external_libraries: false,
                    is_on_bot_java: false,
                    description: String::from(""),
                    xml_tag_aliases: vec![],
                    motor_extras: None,
                    servo_extras: None,
                },
                HardwareDeviceType {
                    flavor: ftc_proto::hardware::device::DeviceFlavor::BuiltIn,
                    xml_tag: String::from("AdafruitColorSensor"),
                    name: String::from("Adafruit Color Sensor"),
                    built_in: false,
                    is_deprecated: false,
                    is_external_libraries: false,
                    is_on_bot_java: false,
                    description: String::from(""),
                    xml_tag_aliases: vec![],
                    motor_extras: None,
                    servo_extras: None,
                },
                HardwareDeviceType {
                    flavor: ftc_proto::hardware::device::DeviceFlavor::I2C,
                    xml_tag: String::from("ControlHubImuBHI260AP"),
                    name: String::from("REV internal IMU (BHI260AP)"),
                    built_in: true,
                    is_deprecated: false,
                    is_external_libraries: false,
                    is_on_bot_java: false,
                    description: String::from("an embedded IMU"),
                    xml_tag_aliases: vec![],
                    motor_extras: None,
                    servo_extras: None,
                },
                HardwareDeviceType {
                    flavor: ftc_proto::hardware::device::DeviceFlavor::I2C,
                    xml_tag: String::from("HuskyLens"),
                    name: String::from("HuskyLens"),
                    built_in: false,
                    is_deprecated: false,
                    is_external_libraries: false,
                    is_on_bot_java: false,
                    description: String::from("HuskyLens Vision Sensor"),
                    xml_tag_aliases: vec![],
                    motor_extras: None,
                    servo_extras: None,
                },
                HardwareDeviceType {
                    flavor: ftc_proto::hardware::device::DeviceFlavor::I2C,
                    xml_tag: String::from("RevColorSensorV3"),
                    name: String::from("REV Color Sensor V3"),
                    built_in: true,
                    is_deprecated: false,
                    is_external_libraries: false,
                    is_on_bot_java: false,
                    description: String::from("a REV Color Sensor V3"),
                    xml_tag_aliases: vec![],
                    motor_extras: None,
                    servo_extras: None,
                },
                HardwareDeviceType {
                    flavor: ftc_proto::hardware::device::DeviceFlavor::BuiltIn,
                    xml_tag: String::from("PulseWidthDevice"),
                    name: String::from("Pulse Width Device"),
                    built_in: false,
                    is_deprecated: false,
                    is_external_libraries: false,
                    is_on_bot_java: false,
                    description: String::from(""),
                    xml_tag_aliases: vec![],
                    motor_extras: None,
                    servo_extras: None,
                },
                HardwareDeviceType {
                    flavor: ftc_proto::hardware::device::DeviceFlavor::DigitalIO,
                    xml_tag: String::from("Led"),
                    name: String::from("LED"),
                    built_in: true,
                    is_deprecated: false,
                    is_external_libraries: false,
                    is_on_bot_java: false,
                    description: String::from("an LED"),
                    xml_tag_aliases: vec![],
                    motor_extras: None,
                    servo_extras: None,
                },
                HardwareDeviceType {
                    flavor: ftc_proto::hardware::device::DeviceFlavor::BuiltIn,
                    xml_tag: String::from("Nothing"),
                    name: String::from("Nothing"),
                    built_in: false,
                    is_deprecated: false,
                    is_external_libraries: false,
                    is_on_bot_java: false,
                    description: String::from(""),
                    xml_tag_aliases: vec![],
                    motor_extras: None,
                    servo_extras: None,
                },
                HardwareDeviceType {
                    flavor: ftc_proto::hardware::device::DeviceFlavor::BuiltIn,
                    xml_tag: String::from("EthernetDevice"),
                    name: String::from("[Unknown]"),
                    built_in: false,
                    is_deprecated: false,
                    is_external_libraries: false,
                    is_on_bot_java: false,
                    description: String::from(""),
                    xml_tag_aliases: vec![],
                    motor_extras: None,
                    servo_extras: None,
                },
                HardwareDeviceType {
                    flavor: ftc_proto::hardware::device::DeviceFlavor::BuiltIn,
                    xml_tag: String::from("<unknown>"),
                    name: String::from("[Unknown]"),
                    built_in: false,
                    is_deprecated: false,
                    is_external_libraries: false,
                    is_on_bot_java: false,
                    description: String::from(""),
                    xml_tag_aliases: vec![],
                    motor_extras: None,
                    servo_extras: None,
                },
                HardwareDeviceType {
                    flavor: ftc_proto::hardware::device::DeviceFlavor::Motor,
                    xml_tag: String::from("Motor"),
                    name: String::from("Unspecified Motor"),
                    built_in: true,
                    is_deprecated: false,
                    is_external_libraries: false,
                    is_on_bot_java: false,
                    description: String::from(""),
                    xml_tag_aliases: vec![],
                    motor_extras: None,
                    servo_extras: None,
                },
                HardwareDeviceType {
                    flavor: ftc_proto::hardware::device::DeviceFlavor::Servo,
                    xml_tag: String::from("RevSPARKMini"),
                    name: String::from("REV SPARKmini Controller"),
                    built_in: true,
                    is_deprecated: false,
                    is_external_libraries: false,
                    is_on_bot_java: false,
                    description: String::from("a REV SPARKmini Motor Controller"),
                    xml_tag_aliases: vec![],
                    motor_extras: None,
                    servo_extras: None,
                },
                HardwareDeviceType {
                    flavor: ftc_proto::hardware::device::DeviceFlavor::BuiltIn,
                    xml_tag: String::from("LynxUsbDevice"),
                    name: String::from("Expansion Hub Portal"),
                    built_in: false,
                    is_deprecated: false,
                    is_external_libraries: false,
                    is_on_bot_java: false,
                    description: String::from(""),
                    xml_tag_aliases: vec![],
                    motor_extras: None,
                    servo_extras: None,
                },
                HardwareDeviceType {
                    flavor: ftc_proto::hardware::device::DeviceFlavor::Servo,
                    xml_tag: String::from("Servo"),
                    name: String::from("Servo"),
                    built_in: true,
                    is_deprecated: false,
                    is_external_libraries: false,
                    is_on_bot_java: false,
                    description: String::from(""),
                    xml_tag_aliases: vec![],
                    motor_extras: None,
                    servo_extras: None,
                },
                HardwareDeviceType {
                    flavor: ftc_proto::hardware::device::DeviceFlavor::BuiltIn,
                    xml_tag: String::from("Webcam"),
                    name: String::from("Webcam"),
                    built_in: false,
                    is_deprecated: false,
                    is_external_libraries: false,
                    is_on_bot_java: false,
                    description: String::from(""),
                    xml_tag_aliases: vec![],
                    motor_extras: None,
                    servo_extras: None,
                },
                HardwareDeviceType {
                    flavor: ftc_proto::hardware::device::DeviceFlavor::Motor,
                    xml_tag: String::from("StudicaMaverick"),
                    name: String::from("Studica Maverick"),
                    built_in: true,
                    is_deprecated: false,
                    is_external_libraries: false,
                    is_on_bot_java: false,
                    description: String::from(""),
                    xml_tag_aliases: vec![],
                    motor_extras: None,
                    servo_extras: None,
                },
                HardwareDeviceType {
                    flavor: ftc_proto::hardware::device::DeviceFlavor::BuiltIn,
                    xml_tag: String::from("Accelerometer"),
                    name: String::from("[Unknown]"),
                    built_in: false,
                    is_deprecated: false,
                    is_external_libraries: false,
                    is_on_bot_java: false,
                    description: String::from(""),
                    xml_tag_aliases: vec![],
                    motor_extras: None,
                    servo_extras: None,
                },
                HardwareDeviceType {
                    flavor: ftc_proto::hardware::device::DeviceFlavor::BuiltIn,
                    xml_tag: String::from("UltrasonicSensor"),
                    name: String::from("[Unknown]"),
                    built_in: false,
                    is_deprecated: false,
                    is_external_libraries: false,
                    is_on_bot_java: false,
                    description: String::from(""),
                    xml_tag_aliases: vec![],
                    motor_extras: None,
                    servo_extras: None,
                },
                HardwareDeviceType {
                    flavor: ftc_proto::hardware::device::DeviceFlavor::BuiltIn,
                    xml_tag: String::from("IrSeekerV3"),
                    name: String::from("MR IR Seeker v3"),
                    built_in: false,
                    is_deprecated: false,
                    is_external_libraries: false,
                    is_on_bot_java: false,
                    description: String::from(""),
                    xml_tag_aliases: vec![],
                    motor_extras: None,
                    servo_extras: None,
                },
                HardwareDeviceType {
                    flavor: ftc_proto::hardware::device::DeviceFlavor::Motor,
                    xml_tag: String::from("NeveRest20Gearmotor"),
                    name: String::from("NeveRest 20 Gearmotor"),
                    built_in: true,
                    is_deprecated: false,
                    is_external_libraries: false,
                    is_on_bot_java: false,
                    description: String::from(""),
                    xml_tag_aliases: vec![],
                    motor_extras: None,
                    servo_extras: None,
                },
                HardwareDeviceType {
                    flavor: ftc_proto::hardware::device::DeviceFlavor::Motor,
                    xml_tag: String::from("RevRoboticsCoreHexMotor"),
                    name: String::from("REV Robotics Core Hex Motor"),
                    built_in: true,
                    is_deprecated: false,
                    is_external_libraries: false,
                    is_on_bot_java: false,
                    description: String::from(""),
                    xml_tag_aliases: vec![],
                    motor_extras: None,
                    servo_extras: None,
                },
                HardwareDeviceType {
                    flavor: ftc_proto::hardware::device::DeviceFlavor::BuiltIn,
                    xml_tag: String::from("LynxColorSensor"),
                    name: String::from("REV Color/Range Sensor"),
                    built_in: false,
                    is_deprecated: false,
                    is_external_libraries: false,
                    is_on_bot_java: false,
                    description: String::from(""),
                    xml_tag_aliases: vec![],
                    motor_extras: None,
                    servo_extras: None,
                },
                HardwareDeviceType {
                    flavor: ftc_proto::hardware::device::DeviceFlavor::I2C,
                    xml_tag: String::from("ModernRoboticsI2cRangeSensor"),
                    name: String::from("MR Range Sensor"),
                    built_in: true,
                    is_deprecated: false,
                    is_external_libraries: false,
                    is_on_bot_java: false,
                    description: String::from("a MR range sensor"),
                    xml_tag_aliases: vec![],
                    motor_extras: None,
                    servo_extras: None,
                },
                HardwareDeviceType {
                    flavor: ftc_proto::hardware::device::DeviceFlavor::I2C,
                    xml_tag: String::from("SparkFunOTOS"),
                    name: String::from("SparkFun OTOS"),
                    built_in: false,
                    is_deprecated: false,
                    is_external_libraries: false,
                    is_on_bot_java: false,
                    description: String::from("SparkFun Qwiic Optical Tracking Odometry Sensor"),
                    xml_tag_aliases: vec![],
                    motor_extras: None,
                    servo_extras: None,
                },
                HardwareDeviceType {
                    flavor: ftc_proto::hardware::device::DeviceFlavor::AnalogSensor,
                    xml_tag: String::from("OpticalDistanceSensor"),
                    name: String::from("MR Optical Distance Sensor"),
                    built_in: true,
                    is_deprecated: false,
                    is_external_libraries: false,
                    is_on_bot_java: false,
                    description: String::from("a Modern Robotics optical distance sensor"),
                    xml_tag_aliases: vec![],
                    motor_extras: None,
                    servo_extras: None,
                },
                HardwareDeviceType {
                    flavor: ftc_proto::hardware::device::DeviceFlavor::Motor,
                    xml_tag: String::from("RevRoboticsUltraplanetaryHDHexMotor"),
                    name: String::from("REV Robotics UltraPlanetary HD Hex Motor"),
                    built_in: true,
                    is_deprecated: false,
                    is_external_libraries: false,
                    is_on_bot_java: false,
                    description: String::from(""),
                    xml_tag_aliases: vec![],
                    motor_extras: None,
                    servo_extras: None,
                },
                HardwareDeviceType {
                    flavor: ftc_proto::hardware::device::DeviceFlavor::BuiltIn,
                    xml_tag: String::from("ColorSensor"),
                    name: String::from("MR Color Sensor"),
                    built_in: false,
                    is_deprecated: false,
                    is_external_libraries: false,
                    is_on_bot_java: false,
                    description: String::from(""),
                    xml_tag_aliases: vec![],
                    motor_extras: None,
                    servo_extras: None,
                },
                HardwareDeviceType {
                    flavor: ftc_proto::hardware::device::DeviceFlavor::BuiltIn,
                    xml_tag: String::from("LynxModule"),
                    name: String::from("Expansion Hub"),
                    built_in: false,
                    is_deprecated: false,
                    is_external_libraries: false,
                    is_on_bot_java: false,
                    description: String::from(""),
                    xml_tag_aliases: vec![],
                    motor_extras: None,
                    servo_extras: None,
                },
                HardwareDeviceType {
                    flavor: ftc_proto::hardware::device::DeviceFlavor::Motor,
                    xml_tag: String::from("NeveRest3.7v1Gearmotor"),
                    name: String::from("NeveRest 3.7 v1 Gearmotor"),
                    built_in: true,
                    is_deprecated: false,
                    is_external_libraries: false,
                    is_on_bot_java: false,
                    description: String::from(""),
                    xml_tag_aliases: vec![],
                    motor_extras: None,
                    servo_extras: None,
                },
                HardwareDeviceType {
                    flavor: ftc_proto::hardware::device::DeviceFlavor::I2C,
                    xml_tag: String::from("REV_VL53L0X_RANGE_SENSOR"),
                    name: String::from("REV 2M Distance Sensor"),
                    built_in: true,
                    is_deprecated: false,
                    is_external_libraries: false,
                    is_on_bot_java: false,
                    description: String::from("REV 2M Distance Sensor"),
                    xml_tag_aliases: vec![],
                    motor_extras: None,
                    servo_extras: None,
                },
                HardwareDeviceType {
                    flavor: ftc_proto::hardware::device::DeviceFlavor::BuiltIn,
                    xml_tag: String::from("Compass"),
                    name: String::from("[Unknown]"),
                    built_in: false,
                    is_deprecated: false,
                    is_external_libraries: false,
                    is_on_bot_java: false,
                    description: String::from(""),
                    xml_tag_aliases: vec![],
                    motor_extras: None,
                    servo_extras: None,
                },
                HardwareDeviceType {
                    flavor: ftc_proto::hardware::device::DeviceFlavor::I2C,
                    xml_tag: String::from("KauaiLabsNavxMicro"),
                    name: String::from("navX Micro"),
                    built_in: true,
                    is_deprecated: false,
                    is_external_libraries: false,
                    is_on_bot_java: false,
                    description: String::from("a navX Micro gyro"),
                    xml_tag_aliases: vec![],
                    motor_extras: None,
                    servo_extras: None,
                },
                HardwareDeviceType {
                    flavor: ftc_proto::hardware::device::DeviceFlavor::I2C,
                    xml_tag: String::from("MaxSonarI2CXL"),
                    name: String::from("MaxSonar I2CXL"),
                    built_in: false,
                    is_deprecated: false,
                    is_external_libraries: false,
                    is_on_bot_java: false,
                    description: String::from(""),
                    xml_tag_aliases: vec![],
                    motor_extras: None,
                    servo_extras: None,
                },
                HardwareDeviceType {
                    flavor: ftc_proto::hardware::device::DeviceFlavor::AnalogSensor,
                    xml_tag: String::from("AnalogInput"),
                    name: String::from("Analog Input"),
                    built_in: true,
                    is_deprecated: false,
                    is_external_libraries: false,
                    is_on_bot_java: false,
                    description: String::from(""),
                    xml_tag_aliases: vec![],
                    motor_extras: None,
                    servo_extras: None,
                },
                HardwareDeviceType {
                    flavor: ftc_proto::hardware::device::DeviceFlavor::I2C,
                    xml_tag: String::from("OctoQuadFTC"),
                    name: String::from("OctoQuadFTC"),
                    built_in: false,
                    is_deprecated: false,
                    is_external_libraries: false,
                    is_on_bot_java: false,
                    description: String::from(""),
                    xml_tag_aliases: vec![],
                    motor_extras: None,
                    servo_extras: None,
                },
                HardwareDeviceType {
                    flavor: ftc_proto::hardware::device::DeviceFlavor::Servo,
                    xml_tag: String::from("ContinuousRotationServo"),
                    name: String::from("Continuous Rotation Servo"),
                    built_in: true,
                    is_deprecated: false,
                    is_external_libraries: false,
                    is_on_bot_java: false,
                    description: String::from(""),
                    xml_tag_aliases: vec![],
                    motor_extras: None,
                    servo_extras: None,
                },
            ]),
        }
    }
}
