# .github/workflows/release.yml
name: Release

on:
  release:
    types: [created]

jobs:
  release-windows:
    name: release windows x64
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
        with:
          cache-all-crates: "true"
      - name: Compile
        run: cargo build --release
      - name: Upload release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/release/ftctui.exe
          asset_name: ftctui_windows_x64.exe
          tag: ${{ github.ref }}

  release-linux:
    name: release linux x64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
        with:
          cache-all-crates: "true"
      - name: Install required libraries
        run: sudo apt update && sudo apt install libudev-dev
      - name: Compile
        run: cargo build --release
      - name: Upload release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/release/ftctui
          asset_name: ftctui_linux_x64
          tag: ${{ github.ref }}
      - name: Download appimagetool
        run: wget github.com/AppImage/appimagetool/releases/download/continuous/appimagetool-x86_64.AppImage && chmod +x ./appimagetool-x86_64.AppImage
      - name: Create appdir
        run: ./create_appdir.sh
      - name: Create appimage
        run: ARCH=x86_64 ./appimagetool-x86_64.AppImage FTCTui.AppDir
      - name: Upload appimage release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./ftctui-x86_64.AppImage
          asset_name: ftctui_linux_x64.AppImage
          tag: ${{ github.ref }}
